#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : contextlib2
Version  : 0.5.4
Release  : 17
URL      : http://pypi.debian.net/contextlib2/contextlib2-0.5.4.tar.gz
Source0  : http://pypi.debian.net/contextlib2/contextlib2-0.5.4.tar.gz
Summary  : Backports and enhancements for the contextlib module
Group    : Development/Tools
License  : Python-2.0
Requires: contextlib2-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
.. image:: https://jazzband.co/static/img/badge.svg
:target: https://jazzband.co/
:alt: Jazzband

%package python
Summary: python components for the contextlib2 package.
Group: Default

%description python
python components for the contextlib2 package.


%prep
%setup -q -n contextlib2-0.5.4

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489027148
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 test_contextlib2.py
%install
export SOURCE_DATE_EPOCH=1489027148
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
